version: "1.0"

services:
  # db:
  #   image: postgres:14.3
  #   restart: always
  #   ports:
  #     - '5432:5432'
  #   environment:
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}
  #     POSTGRES_DB: ${DB_NAME}
  #   container_name: ${DOCKER_CONTAINER_NAME}
  #   volumes:
  #     - ./postgres:/var/lib/postgresql/data

  nginx:
    build: ./nginx
    ports:
      - 8687:80
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    depends_on:
      - server
    restart: "always"

  server:
    build: ./server
    command: sh -c "gunicorn server.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    expose:
      - 8000
    restart: "always"

volumes:
  static_volume:
  media_volume: