# Generated by Django 5.0.6 on 2024-06-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertelegram',
            name='chat_id',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
