# Generated by Django 5.0.6 on 2024-06-17 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='num_cases',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='cases',
            field=models.FileField(blank=True, null=True, upload_to='cases'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='code',
            field=models.FileField(blank=True, null=True, upload_to='code'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
